use GD1C2013
go

DROP TABLE DATACENTER.Devolucion
DROP TABLE DATACENTER.Pasaje
DROP TABLE DATACENTER.Arribo
DROP TABLE DATACENTER.Viaje
DROP TABLE DATACENTER.Butaca
DROP TABLE DATACENTER.PremioPorCanje
DROP TABLE DATACENTER.Canje
DROP TABLE DATACENTER.Premio
DROP TABLE DATACENTER.Paquete
DROP TABLE DATACENTER.Compra
DROP TABLE DATACENTER.TipoTarjeta
DROP TABLE DATACENTER.Recorrido
DROP TABLE DATACENTER.EstadoMicro
DROP TABLE DATACENTER.Micro
DROP TABLE DATACENTER.Servicio
DROP TABLE DATACENTER.Cliente
DROP TABLE DATACENTER.Marca
DROP TABLE DATACENTER.FuncionalidadPorRol
DROP TABLE DATACENTER.Funcionalidad
DROP TABLE DATACENTER.Administrador
DROP TABLE DATACENTER.Ciudad
DROP TABLE DATACENTER.Rol

DROP VIEW Micros_Migrados

DROP PROCEDURE DATACENTER.update_cant_intentos_fallidos

DROP PROCEDURE DATACENTER.insert_Rol

DROP PROCEDURE DATACENTER.insert_funcxrol

DROP PROCEDURE DATACENTER.delete_funcxrol

DROP SCHEMA DATACENTER





